### PR TITLE
Fix CollectionControlDialog control may cause 'System.ArgumentOutOfRangeException'

### PR DESCRIPTION
**Pull request by aaasoft**
In CollectionControlDialog.xaml.cs Line 230 to 235,will cause exception when 'source' is a ICollection and it's count is 0.

Exception StackTrace:
-------------------
   At System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   At System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   At System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   At System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   At System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   At Xceed.Wpf.Toolkit.CollectionControlDialog.Clone(Object source)
   At Xceed.Wpf.Toolkit.CollectionControlDialog.Clone(Object source)
   At Xceed.Wpf.Toolkit.CollectionControlDialog.OnSourceInitialized(EventArgs e)
   At System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   At System.Windows.Window.CreateSourceWindowDuringShow()
   At System.Windows.Window.SafeCreateWindowDuringShow()
   At System.Windows.Window.ShowHelper(Object booleanBox)
   At System.Windows.Window.Show()
   At System.Windows.Window.ShowDialog()
   At Xceed.Wpf.Toolkit.CollectionControlButton.CollectionControlButton_Click(Object sender, RoutedEventArgs e)
   At System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   At System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   At System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   At System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   At System.Windows.Controls.Primitives.ButtonBase.OnClick()
   At System.Windows.Controls.Button.OnClick()
   At System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   At System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   At System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   At System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   At System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   At System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   At System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   At System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   At System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   At System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   At System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   At System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   At System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   At System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   At System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   At System.Windows.Input.InputManager.ProcessStagingArea()
   At System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   At System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   At System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   At System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   At System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   At MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   At MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   At System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   At System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   At System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   At MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   At MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   At System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   At System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   At System.Windows.Application.RunDispatcher(Object ignore)
   At System.Windows.Application.RunInternal(Window window)
   At System.Windows.Application.Run(Window window)
   At System.Windows.Application.Run()

InnerException
---------------------
   At System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   At System.Collections.Generic.List`1.get_Item(Int32 index)
   At System.Collections.ObjectModel.Collection`1.get_Item(Int32 index)

### CODE REVIEW

**Comment by XceedBoucherS** [comment]
Hi,

I can not reproduce. Can you submit a sample please ?
Thank you

**Comment by aaasoft** [comment]
Hi,
I create a sample to reproduce.Run the sample,when you click the CollectionControlButton in the PropertyGrid control,it will cause a Exception.

Sample repo-> https://github.com/aaasoft/wpftoolkit_pull_1332_sample

qq 20180602211255

**Comment by XceedBoucherS** [comment]
Hi,
Thank you for the sample. This issue is already fixed in v3.6.
You can get v3.6 from here : https://xceed.com/xceed-toolkit-plus-for-wpf/
Users of the Plus version have v3.6 (v3.7 to be released real soon)
Users of the free version have v3.3.
Users of the Plus version always have the latest version, more features and fast support.

You can use the Plus version with a free 45 days trial, or use your fix until the free v3.6 is released.

**Comment by aaasoft** [comment]
OK,I will close this pull request.

**Pull request closed without merging**
